name: CI/CD Pipeline Frontend

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. تسجيل الدخول إلى Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. بناء الـ Image وتمرير عنوان الباكيند الداخلي جوة الـ Cluster
      - name: Build and Push Frontend Image (with SHA tag)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: hadeernasser7/smart-frontend:${{ github.sha }}
          build-args: |
            VITE_API_URL=https://smart-backend-fmapeqeueha2gkbv.austriaeast-01.azurewebsites.net
          
      # 3. إعطاء الـ Image تاغ latest ورفعها كنسخة أساسية
      - name: Tag as latest and Push
        run: |
          docker tag hadeernasser7/smart-frontend:${{ github.sha }} hadeernasser7/smart-frontend:latest
          docker push hadeernasser7/smart-frontend:latest
